# Generated by Django 2.2.7 on 2020-06-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200606_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('overview', models.TextField(max_length=80)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Someone's Memorial",
                'verbose_name_plural': 'People Memorials',
            },
        ),
    ]
