# Generated by Django 2.2.7 on 2020-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200606_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='overview',
            field=models.TextField(max_length=250),
        ),
    ]
